elfin_arm_controller:
  type: elfin_rrmc_controllers/RRMCPositionController # position_controllers/JointGroupPositionController # position_controllers/JointTrajectoryController # 
  joints:
     - elfin_joint1
     - elfin_joint2
     - elfin_joint3
     - elfin_joint4
     - elfin_joint5
     - elfin_joint6
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.1

  stop_trajectory_duration: 0.05
  state_publish_rate:  90
  action_monitor_rate: 90

  root_link: elfin_base_link
  tip_link: elfin_end_link
  motion_rate: 1
  damping: 0.2