elfin_arm_controller:
  type: position_controllers/JointTrajectoryController # elfin_rrmc_controllers/RRMCPositionController # 
  joints:
     - elfin_joint1
     - elfin_joint2
     - elfin_joint3
     - elfin_joint4
     - elfin_joint5
     - elfin_joint6

  elfin_joint1: {pid: {p: 200.0, i: 10, d: 10.0, i_clamp: 50, antiwindup: true}}
  elfin_joint2: {pid: {p: 100.0, i:  5, d: 20.0, i_clamp: 50, antiwindup: true}}
  elfin_joint3: {pid: {p: 200.0, i: 10, d:  0.0, i_clamp: 50, antiwindup: true}}
  elfin_joint4: {pid: {p: 200.0, i: 10, d:  0.0, i_clamp: 50, antiwindup: true}}
  elfin_joint5: {pid: {p: 200.0, i: 10, d:  5.0, i_clamp: 50, antiwindup: true}}
  elfin_joint6: {pid: {p: 200.0, i:  5, d:  5.0, i_clamp: 50, antiwindup: true}}

  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.1
  stop_trajectory_duration: 0.05
  state_publish_rate:  25
  action_monitor_rate: 10

  root_link: elfin_base_link
  tip_link: elfin_end_link
  motion_rate: 20
  damping: 0.2
